"use client";

import { useState, type FormEvent } from "react";
import type { PublishingConfig } from "@iorder/core/server/settings/publishing.contract";
import { useAdminToast } from "@/components/admin/ui/admin-feedback";
import { MediaPicker } from "./media-picker";

export function PublishingConfigEditor({ initial }: { initial: PublishingConfig }) {
  const [config, setConfig] = useState(initial); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const { show: showToast } = useAdminToast();
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch("/api/admin/publishing-config", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(config) }); const body = await response.json(); if (response.ok) { showToast("Đã cập nhật cấu hình xuất bản.", "success"); } else { const notice = body.error?.message ?? "Không thể lưu cấu hình."; setMessage(notice); showToast(notice, "error"); } } catch { const notice = "Không kết nối được máy chủ."; setMessage(notice); showToast(notice, "error"); } finally { setBusy(false); } }
  return <form className="grid gap-4" onSubmit={save}><p>URL chính thức giúp tạo canonical, sitemap.xml và robots.txt. Để trống nếu chưa có domain production; website sẽ không tự công bố sitemap.</p><label>URL website chính thức<input className="block w-full rounded border p-2" type="url" value={config.siteUrl ?? ""} onChange={event => setConfig({ ...config, siteUrl: event.target.value.trim() || null })} placeholder="https://www.ten-mien-cua-ban.vn" /></label><label>Tiêu đề mặc định<input className="block w-full rounded border p-2" value={config.defaultTitle ?? ""} onChange={event => setConfig({ ...config, defaultTitle: event.target.value || null })} /></label><label>Mô tả mặc định<textarea className="block w-full rounded border p-2" rows={3} value={config.defaultDescription ?? ""} onChange={event => setConfig({ ...config, defaultDescription: event.target.value || null })} /></label><label className="flex gap-2"><input type="checkbox" checked={config.allowSearchIndexing} onChange={event => setConfig({ ...config, allowSearchIndexing: event.target.checked })} />Cho phép công cụ tìm kiếm index website</label><p>Ảnh chia sẻ mặc định</p><MediaPicker value={config.defaultOgMediaId} onChange={defaultOgMediaId => setConfig({ ...config, defaultOgMediaId })} /><button className="justify-self-start rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50" disabled={busy}>{busy ? "Đang lưu…" : "Lưu cấu hình xuất bản"}</button><p role="status">{message}</p></form>;
}
