import { asc, eq } from "drizzle-orm";
import { getDb } from "@iorder/core/db/client";
import { auditLogs, mediaAssets, partners, testimonials } from "@iorder/core/db/schema";
import type { PartnerInput, TestimonialInput } from "./supporting.contract";

export function listPartners(enabledOnly = false) { return getDb().select({ partner: partners, storageKey: mediaAssets.storageKey, altText: mediaAssets.altText }).from(partners).leftJoin(mediaAssets, eq(partners.logoMediaId, mediaAssets.id)).where(enabledOnly ? eq(partners.isEnabled, true) : undefined).orderBy(asc(partners.sortOrder), asc(partners.name)); }
export function listTestimonials(enabledOnly = false) { return getDb().select({ testimonial: testimonials, storageKey: mediaAssets.storageKey, altText: mediaAssets.altText }).from(testimonials).leftJoin(mediaAssets, eq(testimonials.avatarMediaId, mediaAssets.id)).where(enabledOnly ? eq(testimonials.isEnabled, true) : undefined).orderBy(asc(testimonials.sortOrder), asc(testimonials.authorName)); }
export function savePartner(id: string | null, values: PartnerInput, userId: string) { return getDb().transaction(async tx => { const [row] = id ? await tx.update(partners).set({ ...values, updatedAt: new Date() }).where(eq(partners.id, id)).returning() : await tx.insert(partners).values(values).returning(); if (!row) return undefined; await tx.insert(auditLogs).values({ userId, action: id ? "partner.update" : "partner.create", entityType: "partner", entityId: row.id, afterData: values }); return row.id; }); }
export function saveTestimonial(id: string | null, values: TestimonialInput, userId: string) { return getDb().transaction(async tx => { const [row] = id ? await tx.update(testimonials).set({ ...values, updatedAt: new Date() }).where(eq(testimonials.id, id)).returning() : await tx.insert(testimonials).values(values).returning(); if (!row) return undefined; await tx.insert(auditLogs).values({ userId, action: id ? "testimonial.update" : "testimonial.create", entityType: "testimonial", entityId: row.id, afterData: values }); return row.id; }); }
